services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-api:latest
    container_name: nest-api-app
    restart: unless-stopped
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    container_name: nest-api-postgres-prod
    ports:
      - "5434:5432"

  redis:
    container_name: nest-api-redis-prod
    ports:
      - "6381:6379"

networks:
  default:
    name: nest-api-prod
